import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";

const myFontRegular = localFont({
  src: '/fonts/BeVietnamPro-Regular.ttf',
  weight: '400',
  variable: '--font-myFont-regular',

})

export const metadata: Metadata = {
  title: "AI Courses Generator",
  description: "Generated by HTShun",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFontRegular} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
